# Codecov configuration for proper GitHub status check reporting
codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        threshold: 50%
        informational: true    # Add this line to always post status
    patch:
      default:               # Change from 'false' to explicit config
        threshold: 0%
        informational: true

comment:
  layout: "header"
  require_changes: false
  behavior: default