name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.9, "3.10", "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Additional info about the build
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          environment-name: test
          condarc: |
            channels:
              - conda-forge
              - defaults
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install -e . --no-deps
          python -m pip install -r requirements.txt
          python -m pip install qiskit_qasm3_import
          micromamba list

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v --cov=qem_ml --cov-report=xml --color=yes qem_ml/tests/

      - name: Check coverage report
        run: head -n 20 coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
          branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
          slug: MaxLinville/qem_ml
          verbose: true
